name: tinyroberta-distillation-qa-es
channels:
  - defaults
  - huggingface
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - conda
  - setuptools
  - pip
  - wheel
  - conda-content-trust
  - conda-libmamba-solver
  - pytorch
  - pytorch-cuda=12.1
  - torchaudio
  - torchvision
  - transformers
  - accelerate
  - evaluate
  - datasets
  - scikit-learn
  - fsspec==2023.9.2